export interface Env {
  DB: D1Database

  WEB_ORIGIN: string

  BETTER_AUTH_SECRET: string
  BETTER_AUTH_URL: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  FACEBOOK_CLIENT_ID: string
  FACEBOOK_CLIENT_SECRET: string

  GOOGLE_SERVICE_ACCOUNT_EMAIL: string
  GOOGLE_SERVICE_ACCOUNT_KEY: string
  ACCOUNTS_SHEET_ID: string
  CONTENT_DRIVE_FOLDER_ID: string
}
