/**
 * The brand page's "flyer's alpona" block, drawn by the app's own components.
 *
 * web/public/brand-identity.html is a static page, so it can't use the React
 * Alpona set; this renders those motifs and bands to static SVG (white on the
 * jaba band, ids made unique) and replaces the block in place — so /brandcolours
 * shows exactly what the site draws. Rerun after changing a motif or a band:
 *
 *     npx tsx --tsconfig web/tsconfig.app.json scripts/brand-alpona.mts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { createElement as h } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { Alpona, ChevronBorder, DotBorder, HandDrawn, LeafBorder, TaraBorder, TempleBorder } from '@/components/Alpona'

let n = 0
/** Static markup, made brand-page ready: white for currentColor, no app classes, unique ids. */
const svg = (el: Parameters<typeof renderToStaticMarkup>[0], label: string) => {
  n++
  let s = renderToStaticMarkup(el)
  s = s.replace(/currentColor/g, '#FFFFFF').replace(/ class="[^"]*"/g, '')
  // useId ids (":R0:" …) repeat between separate renders — make each piece's own
  s = s.replace(/id="([^"]+)"/g, (_, id) => `id="bi${n}-${id.replace(/[^a-zA-Z0-9]/g, '')}"`)
  s = s.replace(/url\(#(?!alpona-hand)([^)]+)\)/g, (_, id) => `url(#bi${n}-${id.replace(/[^a-zA-Z0-9]/g, '')})`)
  s = s.replace(/aria-hidden="true"/, `role="img" aria-label="${label}"`)
  return s
}

const motifs: [Parameters<typeof Alpona>[0]['name'], string, string, string][] = [
  ['dhak', 'Dhak', 'ঢাক', 'The pujo drum, laced end to end, its feather plume rising'],
  ['chakra', 'Chakra', 'চক্র', 'A mandala ring of filled petals — Maa’s face sits in it'],
  ['konaMandala', 'Kona mandala', 'কোণের মণ্ডল', 'A quarter alpona grown out of a corner, ring on ring'],
  ['kona', 'Kona', 'কোণ', 'A corner curl: double line, a kalka in its crook'],
  ['taraKona', 'Tara kona', 'তারা', 'The temple band’s corner block, a tara in a square'],
  ['shiuli', 'Shiuli', 'শিউলি', 'The night jasmine of Sharat, fallen at dawn'],
]
const cells = motifs
  .map(
    ([name, en, bn, note]) => `    <figure class="alp-cell" role="listitem">
      ${svg(h(Alpona, { name, hand: true, strokeWidth: 2 }), en)}
      <figcaption><b>${en}</b> · ${bn}<br>${note}</figcaption>
    </figure>`,
  )
  .join('\n')

const bands: [typeof TempleBorder, string, string, string][] = [
  [TempleBorder, 'Temple band', 'মন্দির পাড়', 'triangles holding filled leaves, a bindu in every gap, ruled both sides — round the whole field'],
  [LeafBorder, 'Leaf band', 'পাতার পাড়', 'a rule hung with filled leaves pointing in — round a panel inside the alpona'],
  [TaraBorder, 'Tara row', 'তারার সারি', 'star flowers, eight spokes tipped with bindus'],
  [ChevronBorder, 'Chevron chain', '', 'the footer’s chevron, a bindu between each'],
  [DotBorder, 'Dot line', '', 'rice-paste dots — the inner rule of a frame'],
]
const strips = bands
  .map(
    ([Band, en, bn, note]) => `    <figure>
      ${svg(h(Band, { hand: true }), en)}
      <figcaption><b>${en}</b>${bn ? ` · ${bn}` : ''} — ${note}</figcaption>
    </figure>`,
  )
  .join('\n')

const filter = renderToStaticMarkup(h(HandDrawn)).replace(/ class="[^"]*"/g, ' style="position:absolute"')

const block = `  <!-- ── The flyer's alpona — generated by scripts/brand-alpona.mts from web/src/components/Alpona.tsx; rerun it, don't hand-edit ── -->
  <p class="lede" style="margin-top:22px">Fuller, as the rice paste is laid on at the pandal — drawn for the
  cultural evenings' flyer (<code>/cultural/flyer/01</code>): filled petals and leaves where the paste is
  thick, borders built up in layers, and every line through a rice-paste filter so it wavers a little, as a
  finger-drawn line does (<code>hand</code> on any motif or border, with <code>&lt;HandDrawn /&gt;</code>
  once on the page).</p>
  ${filter}
  <div class="alp-grid alp-new" role="list">
${cells}
  </div>
  <div class="alp-borders alp-new">
${strips}
  </div>

`
const PAGE = new URL('../web/public/brand-identity.html', import.meta.url)
const page = readFileSync(PAGE, 'utf8')
const START = "  <!-- ── The flyer's alpona"
const END = '  <h2 class="serif">On a phone, where it will live</h2>'
const from = page.indexOf(START)
const to = page.indexOf(END)
if (from < 0 || to < 0 || to < from) throw new Error('brand-identity.html: block markers not found')
writeFileSync(PAGE, page.slice(0, from) + block + page.slice(to))
console.log('brand-identity.html: flyer alpona block regenerated')
